const express = require('express')
const { createFood, updateFood, deleteFood, getAllFood, getFoodByName, getAllUserFood } = require('../controllers/foodController')
const { requireAuthentication } = require('../middlewares/authCheck')
const router = express.Router()
router.post('/create-food',createFood)
router.patch('/update-food/:id',requireAuthentication,updateFood)
router.patch('/delete-food/:id',requireAuthentication,deleteFood)
router.get('/get-all-user-food/:id',requireAuthentication,getAllUserFood)
router.get('/get-all-food',getAllFood)
router.get('/get-food',getFoodByName)
module.exports = router
