const express = require('express')
const { createMeal, getAllFoodMealByDate, deleteFoodofMeal } = require('../controllers/mealController')
const { requireAuthentication } = require('../middlewares/authCheck')
const router = express.Router()
router.post('/create-meal',requireAuthentication,createMeal)
router.get('/get-meal',requireAuthentication,getAllFoodMealByDate)
router.patch('/remove-food/:id',deleteFoodofMeal)
// router.patch('/update-food/:id',requireAuthentication,updateFood)
// router.patch('/delete-food/:id',requireAuthentication,deleteFood)
// router.get('/get-all-user-food/:id',requireAuthentication,getAllUserFood)
// router.get('/get-all-food',getAllFood)
// router.get('/search-food',getFoodByName)
// router.get('/search-user-food',requireAuthentication,getUserFoodByName)
module.exports = router
