const express = require('express')
const { createSleep, getSleepLog } = require('../controllers/sleepController')
const router = express.Router()
router.post('/create-sleep', createSleep)
router.get('/get-sleep-week', getSleepLog)
// router.get('/get-water-month',getWaterLogByMonth)
// router.get('/get-water-week-month',getWaterWeekLogByMonth)
// router.get('/get-water-year',getWaterMonthLogByYear)
// router.patch('/remove-water-log/:id',deleteDrink)
module.exports = router
